// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_DataInfoSrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

// 获取数据信息的请求
type DataInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataInfoRequest) Reset()         { *m = DataInfoRequest{} }
func (m *DataInfoRequest) String() string { return proto.CompactTextString(m) }
func (*DataInfoRequest) ProtoMessage()    {}
func (*DataInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *DataInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataInfoRequest.Unmarshal(m, b)
}
func (m *DataInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataInfoRequest.Marshal(b, m, deterministic)
}
func (m *DataInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataInfoRequest.Merge(m, src)
}
func (m *DataInfoRequest) XXX_Size() int {
	return xxx_messageInfo_DataInfoRequest.Size(m)
}
func (m *DataInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataInfoRequest proto.InternalMessageInfo

// 获取数据信息的响应
type DataInfoResponse struct {
	// 错误码
	Errno string `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	// 错误信息
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 返回的数据切片
	Data                 []*DataInfoResponse_Areas `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DataInfoResponse) Reset()         { *m = DataInfoResponse{} }
func (m *DataInfoResponse) String() string { return proto.CompactTextString(m) }
func (*DataInfoResponse) ProtoMessage()    {}
func (*DataInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *DataInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataInfoResponse.Unmarshal(m, b)
}
func (m *DataInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataInfoResponse.Marshal(b, m, deterministic)
}
func (m *DataInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataInfoResponse.Merge(m, src)
}
func (m *DataInfoResponse) XXX_Size() int {
	return xxx_messageInfo_DataInfoResponse.Size(m)
}
func (m *DataInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataInfoResponse proto.InternalMessageInfo

func (m *DataInfoResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *DataInfoResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *DataInfoResponse) GetData() []*DataInfoResponse_Areas {
	if m != nil {
		return m.Data
	}
	return nil
}

// 地区消息对象
type DataInfoResponse_Areas struct {
	// 地区ID
	Aid int32 `protobuf:"varint,1,opt,name=Aid,proto3" json:"Aid,omitempty"`
	// 地区名称
	Aname                string   `protobuf:"bytes,2,opt,name=Aname,proto3" json:"Aname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataInfoResponse_Areas) Reset()         { *m = DataInfoResponse_Areas{} }
func (m *DataInfoResponse_Areas) String() string { return proto.CompactTextString(m) }
func (*DataInfoResponse_Areas) ProtoMessage()    {}
func (*DataInfoResponse_Areas) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2, 0}
}

func (m *DataInfoResponse_Areas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataInfoResponse_Areas.Unmarshal(m, b)
}
func (m *DataInfoResponse_Areas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataInfoResponse_Areas.Marshal(b, m, deterministic)
}
func (m *DataInfoResponse_Areas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataInfoResponse_Areas.Merge(m, src)
}
func (m *DataInfoResponse_Areas) XXX_Size() int {
	return xxx_messageInfo_DataInfoResponse_Areas.Size(m)
}
func (m *DataInfoResponse_Areas) XXX_DiscardUnknown() {
	xxx_messageInfo_DataInfoResponse_Areas.DiscardUnknown(m)
}

var xxx_messageInfo_DataInfoResponse_Areas proto.InternalMessageInfo

func (m *DataInfoResponse_Areas) GetAid() int32 {
	if m != nil {
		return m.Aid
	}
	return 0
}

func (m *DataInfoResponse_Areas) GetAname() string {
	if m != nil {
		return m.Aname
	}
	return ""
}

// 获取首页轮播图片的请求
type IndexRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexRequest) Reset()         { *m = IndexRequest{} }
func (m *IndexRequest) String() string { return proto.CompactTextString(m) }
func (*IndexRequest) ProtoMessage()    {}
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *IndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexRequest.Unmarshal(m, b)
}
func (m *IndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexRequest.Marshal(b, m, deterministic)
}
func (m *IndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexRequest.Merge(m, src)
}
func (m *IndexRequest) XXX_Size() int {
	return xxx_messageInfo_IndexRequest.Size(m)
}
func (m *IndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexRequest proto.InternalMessageInfo

// 获取首页轮播图片的响应
type IndexResponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Max                  []byte   `protobuf:"bytes,3,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexResponse) Reset()         { *m = IndexResponse{} }
func (m *IndexResponse) String() string { return proto.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()    {}
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *IndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexResponse.Unmarshal(m, b)
}
func (m *IndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexResponse.Marshal(b, m, deterministic)
}
func (m *IndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexResponse.Merge(m, src)
}
func (m *IndexResponse) XXX_Size() int {
	return xxx_messageInfo_IndexResponse.Size(m)
}
func (m *IndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexResponse proto.InternalMessageInfo

func (m *IndexResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *IndexResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *IndexResponse) GetMax() []byte {
	if m != nil {
		return m.Max
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.DataInfoSrv.Message")
	proto.RegisterType((*DataInfoRequest)(nil), "go.micro.srv.DataInfoSrv.DataInfoRequest")
	proto.RegisterType((*DataInfoResponse)(nil), "go.micro.srv.DataInfoSrv.DataInfoResponse")
	proto.RegisterType((*DataInfoResponse_Areas)(nil), "go.micro.srv.DataInfoSrv.DataInfoResponse.Areas")
	proto.RegisterType((*IndexRequest)(nil), "go.micro.srv.DataInfoSrv.IndexRequest")
	proto.RegisterType((*IndexResponse)(nil), "go.micro.srv.DataInfoSrv.IndexResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x35, 0xc6, 0x34, 0x3a, 0x56, 0x8d, 0x8b, 0x48, 0x48, 0x2f, 0x21, 0x07, 0x8d, 0x1e, 0xb6,
	0x52, 0xbf, 0x20, 0xd0, 0x50, 0x7a, 0x08, 0x42, 0x3c, 0x7b, 0xd8, 0xda, 0x31, 0x14, 0x4c, 0x36,
	0xee, 0xae, 0x25, 0x7e, 0x99, 0x3f, 0xe1, 0x47, 0xc9, 0x6e, 0x12, 0x14, 0xa1, 0x58, 0x7a, 0xda,
	0x79, 0xc3, 0xbc, 0x79, 0xef, 0x0d, 0x0b, 0xa3, 0x5a, 0x70, 0xc5, 0xc7, 0xd8, 0xb0, 0xb2, 0x7e,
	0xc5, 0xfe, 0xa5, 0xa6, 0x4b, 0xfc, 0x82, 0xd3, 0x72, 0xf5, 0x2c, 0x38, 0x95, 0x62, 0x4d, 0xa7,
	0x4c, 0xb1, 0x79, 0xf5, 0xc2, 0x1f, 0xc5, 0x3a, 0x1a, 0x81, 0x9b, 0xa1, 0x94, 0xac, 0x40, 0xe2,
	0x81, 0x2d, 0xd9, 0x87, 0x6f, 0x85, 0x56, 0x7c, 0x94, 0xeb, 0x32, 0x3a, 0x87, 0xb3, 0x7e, 0x36,
	0xc7, 0xb7, 0x77, 0x94, 0x2a, 0xfa, 0xb4, 0xc0, 0xfb, 0xe9, 0xc9, 0x9a, 0x57, 0x12, 0xc9, 0x05,
	0x38, 0xa9, 0x10, 0x15, 0xef, 0xb8, 0x2d, 0x20, 0x97, 0x30, 0x48, 0x85, 0xc8, 0x64, 0xe1, 0xef,
	0x9b, 0x76, 0x87, 0xc8, 0x14, 0x0e, 0xf4, 0x06, 0xdf, 0x0e, 0xed, 0xf8, 0x78, 0x72, 0x47, 0x37,
	0x79, 0xa3, 0x7f, 0x75, 0x68, 0x22, 0x90, 0xc9, 0xdc, 0xb0, 0x83, 0x31, 0x38, 0x06, 0x6a, 0xdb,
	0xc9, 0x6a, 0x69, 0xa4, 0x9d, 0x5c, 0x97, 0xda, 0x4e, 0x52, 0xb1, 0x12, 0x3b, 0xdd, 0x16, 0x44,
	0xa7, 0x30, 0x9c, 0x57, 0x4b, 0x6c, 0xfa, 0x24, 0x0f, 0x70, 0xd2, 0xe1, 0x9d, 0x52, 0x78, 0x60,
	0x67, 0xac, 0xf1, 0xed, 0xd0, 0x8a, 0x87, 0xb9, 0x2e, 0x27, 0x5f, 0x16, 0xb8, 0x69, 0x7b, 0x76,
	0xb2, 0x00, 0x77, 0x86, 0x4a, 0x1b, 0x24, 0x37, 0xdb, 0x04, 0x34, 0x96, 0x82, 0xdb, 0xed, 0x6f,
	0x11, 0xed, 0x91, 0x27, 0x38, 0x9c, 0xa1, 0x32, 0x19, 0xc8, 0xd5, 0x66, 0xe6, 0xef, 0xd0, 0xc1,
	0xf5, 0xbf, 0x73, 0xfd, 0xfa, 0xc5, 0xc0, 0x7c, 0x9d, 0xfb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x2d, 0x53, 0xdc, 0x7a, 0x59, 0x02, 0x00, 0x00,
}
