// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_VerifyCodeSrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

// 图片验证码的请求
type ImageCodeRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageCodeRequest) Reset()         { *m = ImageCodeRequest{} }
func (m *ImageCodeRequest) String() string { return proto.CompactTextString(m) }
func (*ImageCodeRequest) ProtoMessage()    {}
func (*ImageCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *ImageCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageCodeRequest.Unmarshal(m, b)
}
func (m *ImageCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageCodeRequest.Marshal(b, m, deterministic)
}
func (m *ImageCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageCodeRequest.Merge(m, src)
}
func (m *ImageCodeRequest) XXX_Size() int {
	return xxx_messageInfo_ImageCodeRequest.Size(m)
}
func (m *ImageCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageCodeRequest proto.InternalMessageInfo

func (m *ImageCodeRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// 图片验证码的响应
type ImageCodeResponse struct {
	Errno  string `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// Pix []uint8
	// 图片的结构元素
	Pix []byte `protobuf:"bytes,3,opt,name=Pix,proto3" json:"Pix,omitempty"`
	// Stride int
	// 图片的跨度
	Stride               int64                    `protobuf:"varint,4,opt,name=Stride,proto3" json:"Stride,omitempty"`
	Min                  *ImageCodeResponse_Point `protobuf:"bytes,5,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *ImageCodeResponse_Point `protobuf:"bytes,6,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ImageCodeResponse) Reset()         { *m = ImageCodeResponse{} }
func (m *ImageCodeResponse) String() string { return proto.CompactTextString(m) }
func (*ImageCodeResponse) ProtoMessage()    {}
func (*ImageCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *ImageCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageCodeResponse.Unmarshal(m, b)
}
func (m *ImageCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageCodeResponse.Marshal(b, m, deterministic)
}
func (m *ImageCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageCodeResponse.Merge(m, src)
}
func (m *ImageCodeResponse) XXX_Size() int {
	return xxx_messageInfo_ImageCodeResponse.Size(m)
}
func (m *ImageCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImageCodeResponse proto.InternalMessageInfo

func (m *ImageCodeResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *ImageCodeResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ImageCodeResponse) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *ImageCodeResponse) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *ImageCodeResponse) GetMin() *ImageCodeResponse_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *ImageCodeResponse) GetMax() *ImageCodeResponse_Point {
	if m != nil {
		return m.Max
	}
	return nil
}

// 坐标
// 用来代替Point
type ImageCodeResponse_Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageCodeResponse_Point) Reset()         { *m = ImageCodeResponse_Point{} }
func (m *ImageCodeResponse_Point) String() string { return proto.CompactTextString(m) }
func (*ImageCodeResponse_Point) ProtoMessage()    {}
func (*ImageCodeResponse_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2, 0}
}

func (m *ImageCodeResponse_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageCodeResponse_Point.Unmarshal(m, b)
}
func (m *ImageCodeResponse_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageCodeResponse_Point.Marshal(b, m, deterministic)
}
func (m *ImageCodeResponse_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageCodeResponse_Point.Merge(m, src)
}
func (m *ImageCodeResponse_Point) XXX_Size() int {
	return xxx_messageInfo_ImageCodeResponse_Point.Size(m)
}
func (m *ImageCodeResponse_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageCodeResponse_Point.DiscardUnknown(m)
}

var xxx_messageInfo_ImageCodeResponse_Point proto.InternalMessageInfo

func (m *ImageCodeResponse_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ImageCodeResponse_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

// 短信验证码的请求
type SmsCodeRequest struct {
	// 手机号
	Mobile string `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	// 图片验证码的值
	ImageCode string `protobuf:"bytes,2,opt,name=imageCode,proto3" json:"imageCode,omitempty"`
	// uuid
	Uuid                 string   `protobuf:"bytes,3,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsCodeRequest) Reset()         { *m = SmsCodeRequest{} }
func (m *SmsCodeRequest) String() string { return proto.CompactTextString(m) }
func (*SmsCodeRequest) ProtoMessage()    {}
func (*SmsCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *SmsCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsCodeRequest.Unmarshal(m, b)
}
func (m *SmsCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsCodeRequest.Marshal(b, m, deterministic)
}
func (m *SmsCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsCodeRequest.Merge(m, src)
}
func (m *SmsCodeRequest) XXX_Size() int {
	return xxx_messageInfo_SmsCodeRequest.Size(m)
}
func (m *SmsCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsCodeRequest proto.InternalMessageInfo

func (m *SmsCodeRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SmsCodeRequest) GetImageCode() string {
	if m != nil {
		return m.ImageCode
	}
	return ""
}

func (m *SmsCodeRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// 短信验证码的响应
type SmsCodeResponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsCodeResponse) Reset()         { *m = SmsCodeResponse{} }
func (m *SmsCodeResponse) String() string { return proto.CompactTextString(m) }
func (*SmsCodeResponse) ProtoMessage()    {}
func (*SmsCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *SmsCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsCodeResponse.Unmarshal(m, b)
}
func (m *SmsCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsCodeResponse.Marshal(b, m, deterministic)
}
func (m *SmsCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsCodeResponse.Merge(m, src)
}
func (m *SmsCodeResponse) XXX_Size() int {
	return xxx_messageInfo_SmsCodeResponse.Size(m)
}
func (m *SmsCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmsCodeResponse proto.InternalMessageInfo

func (m *SmsCodeResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *SmsCodeResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.VerifyCodeSrv.Message")
	proto.RegisterType((*ImageCodeRequest)(nil), "go.micro.srv.VerifyCodeSrv.ImageCodeRequest")
	proto.RegisterType((*ImageCodeResponse)(nil), "go.micro.srv.VerifyCodeSrv.ImageCodeResponse")
	proto.RegisterType((*ImageCodeResponse_Point)(nil), "go.micro.srv.VerifyCodeSrv.ImageCodeResponse.Point")
	proto.RegisterType((*SmsCodeRequest)(nil), "go.micro.srv.VerifyCodeSrv.SmsCodeRequest")
	proto.RegisterType((*SmsCodeResponse)(nil), "go.micro.srv.VerifyCodeSrv.SmsCodeResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xdd, 0xa6, 0x4d, 0xe9, 0x58, 0xb4, 0x2e, 0x52, 0x42, 0xea, 0x21, 0x44, 0x90, 0xe0,
	0x9f, 0x08, 0xed, 0x03, 0x78, 0x90, 0x50, 0x3c, 0x04, 0x4a, 0x8a, 0x1e, 0xbc, 0xa5, 0x76, 0x0c,
	0x0b, 0x4d, 0xb6, 0xee, 0xa6, 0x25, 0x79, 0x19, 0xdf, 0xcd, 0x37, 0x91, 0x6c, 0xb7, 0xb5, 0x22,
	0x4a, 0xd5, 0x53, 0xe6, 0x1b, 0xbe, 0x9d, 0xd9, 0xef, 0x47, 0x16, 0x7a, 0x73, 0xc1, 0x73, 0x7e,
	0x8d, 0x45, 0x9c, 0xce, 0x67, 0xb8, 0xfe, 0xfa, 0xaa, 0x4b, 0xed, 0x84, 0xfb, 0x29, 0x7b, 0x12,
	0xdc, 0x97, 0x62, 0xe9, 0x3f, 0xa0, 0x60, 0xcf, 0xe5, 0x2d, 0x9f, 0xe2, 0x58, 0x2c, 0xdd, 0x1e,
	0x34, 0x43, 0x94, 0x32, 0x4e, 0x90, 0x76, 0xc0, 0x90, 0x71, 0x69, 0x11, 0x87, 0x78, 0xad, 0xa8,
	0x2a, 0xdd, 0x33, 0xe8, 0xdc, 0xa5, 0x71, 0x82, 0x95, 0x39, 0xc2, 0x97, 0x05, 0xca, 0x9c, 0x52,
	0xa8, 0xdf, 0x2f, 0xd8, 0x54, 0xdb, 0x54, 0xed, 0xbe, 0xd6, 0xe0, 0x68, 0xcb, 0x28, 0xe7, 0x3c,
	0x93, 0x48, 0x8f, 0xa1, 0x11, 0x08, 0x91, 0x71, 0x6d, 0x5d, 0x09, 0xda, 0x05, 0x33, 0x10, 0x22,
	0x94, 0x89, 0x55, 0x53, 0x6d, 0xad, 0xaa, 0xed, 0x23, 0x56, 0x58, 0x86, 0x43, 0xbc, 0x76, 0x54,
	0x95, 0x95, 0x73, 0x9c, 0x0b, 0x36, 0x45, 0xab, 0xee, 0x10, 0xcf, 0x88, 0xb4, 0xa2, 0x01, 0x18,
	0x21, 0xcb, 0xac, 0x86, 0x43, 0xbc, 0xfd, 0xfe, 0xc0, 0xff, 0x3e, 0x9c, 0xff, 0xe5, 0x4e, 0xfe,
	0x88, 0xb3, 0x2c, 0x8f, 0xaa, 0xf3, 0x6a, 0x4c, 0x5c, 0x58, 0xe6, 0x7f, 0xc6, 0xc4, 0x85, 0x7d,
	0x0a, 0x0d, 0xa5, 0x68, 0x1b, 0x48, 0xa1, 0xa2, 0x1a, 0x11, 0x29, 0x2a, 0x55, 0xaa, 0x84, 0x46,
	0x44, 0x4a, 0xf7, 0x11, 0x0e, 0xc6, 0xa9, 0xdc, 0xc6, 0xd8, 0x05, 0x33, 0xe4, 0x13, 0x36, 0x43,
	0x4d, 0x47, 0x2b, 0x7a, 0x02, 0x2d, 0xb6, 0x5e, 0xa7, 0x09, 0x7d, 0x34, 0x36, 0xf0, 0x8d, 0x2d,
	0xf8, 0x37, 0x70, 0xb8, 0x99, 0xfd, 0x17, 0xf2, 0xfd, 0x37, 0x02, 0xcd, 0x60, 0xf5, 0xc3, 0xd0,
	0x14, 0xda, 0x43, 0xcc, 0x37, 0x81, 0xe9, 0xe5, 0x8e, 0x5c, 0x54, 0x28, 0xfb, 0xea, 0x57, 0x14,
	0xdd, 0x3d, 0x9a, 0x00, 0x0c, 0x31, 0xd7, 0xd7, 0xa7, 0xe7, 0x3f, 0x1d, 0xff, 0xcc, 0xcf, 0xbe,
	0xd8, 0xc9, 0xbb, 0x5e, 0x34, 0x31, 0xd5, 0x4b, 0x18, 0xbc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x2d,
	0xa0, 0x59, 0x2d, 0x28, 0x03, 0x00, 0x00,
}
