// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/example/example.proto

/*
Package go_micro_srv_VerifyCodeSrv is a generated protocol buffer package.

It is generated from these files:
	proto/example/example.proto

It has these top-level messages:
	Message
	ImageCodeRequest
	ImageCodeResponse
	SmsCodeRequest
	SmsCodeResponse
*/
package go_micro_srv_VerifyCodeSrv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Example service

type ExampleService interface {
	// 获取图片验证码
	GetImageCode(ctx context.Context, in *ImageCodeRequest, opts ...client.CallOption) (*ImageCodeResponse, error)
	// 获取短信验证码
	GetSmsCode(ctx context.Context, in *SmsCodeRequest, opts ...client.CallOption) (*SmsCodeResponse, error)
}

type exampleService struct {
	c    client.Client
	name string
}

func NewExampleService(name string, c client.Client) ExampleService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.VerifyCodeSrv"
	}
	return &exampleService{
		c:    c,
		name: name,
	}
}

func (c *exampleService) GetImageCode(ctx context.Context, in *ImageCodeRequest, opts ...client.CallOption) (*ImageCodeResponse, error) {
	req := c.c.NewRequest(c.name, "Example.GetImageCode", in)
	out := new(ImageCodeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) GetSmsCode(ctx context.Context, in *SmsCodeRequest, opts ...client.CallOption) (*SmsCodeResponse, error) {
	req := c.c.NewRequest(c.name, "Example.GetSmsCode", in)
	out := new(SmsCodeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Example service

type ExampleHandler interface {
	// 获取图片验证码
	GetImageCode(context.Context, *ImageCodeRequest, *ImageCodeResponse) error
	// 获取短信验证码
	GetSmsCode(context.Context, *SmsCodeRequest, *SmsCodeResponse) error
}

func RegisterExampleHandler(s server.Server, hdlr ExampleHandler, opts ...server.HandlerOption) error {
	type example interface {
		GetImageCode(ctx context.Context, in *ImageCodeRequest, out *ImageCodeResponse) error
		GetSmsCode(ctx context.Context, in *SmsCodeRequest, out *SmsCodeResponse) error
	}
	type Example struct {
		example
	}
	h := &exampleHandler{hdlr}
	return s.Handle(s.NewHandler(&Example{h}, opts...))
}

type exampleHandler struct {
	ExampleHandler
}

func (h *exampleHandler) GetImageCode(ctx context.Context, in *ImageCodeRequest, out *ImageCodeResponse) error {
	return h.ExampleHandler.GetImageCode(ctx, in, out)
}

func (h *exampleHandler) GetSmsCode(ctx context.Context, in *SmsCodeRequest, out *SmsCodeResponse) error {
	return h.ExampleHandler.GetSmsCode(ctx, in, out)
}
