// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_HouseSrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

// 获取当前用户发布的房源信息的请求
type UserHousesRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserHousesRequest) Reset()         { *m = UserHousesRequest{} }
func (m *UserHousesRequest) String() string { return proto.CompactTextString(m) }
func (*UserHousesRequest) ProtoMessage()    {}
func (*UserHousesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *UserHousesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserHousesRequest.Unmarshal(m, b)
}
func (m *UserHousesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserHousesRequest.Marshal(b, m, deterministic)
}
func (m *UserHousesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserHousesRequest.Merge(m, src)
}
func (m *UserHousesRequest) XXX_Size() int {
	return xxx_messageInfo_UserHousesRequest.Size(m)
}
func (m *UserHousesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserHousesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserHousesRequest proto.InternalMessageInfo

func (m *UserHousesRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

// 获取当前用户发布的房源信息的响应
type UserHousesResponse struct {
	Errno  string `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 查询到的完整数据的二进制流
	Mix                  []byte   `protobuf:"bytes,3,opt,name=Mix,proto3" json:"Mix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserHousesResponse) Reset()         { *m = UserHousesResponse{} }
func (m *UserHousesResponse) String() string { return proto.CompactTextString(m) }
func (*UserHousesResponse) ProtoMessage()    {}
func (*UserHousesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *UserHousesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserHousesResponse.Unmarshal(m, b)
}
func (m *UserHousesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserHousesResponse.Marshal(b, m, deterministic)
}
func (m *UserHousesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserHousesResponse.Merge(m, src)
}
func (m *UserHousesResponse) XXX_Size() int {
	return xxx_messageInfo_UserHousesResponse.Size(m)
}
func (m *UserHousesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserHousesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserHousesResponse proto.InternalMessageInfo

func (m *UserHousesResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *UserHousesResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *UserHousesResponse) GetMix() []byte {
	if m != nil {
		return m.Mix
	}
	return nil
}

// 发布房源的请求
type PostHousesRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	Max                  []byte   `protobuf:"bytes,2,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostHousesRequest) Reset()         { *m = PostHousesRequest{} }
func (m *PostHousesRequest) String() string { return proto.CompactTextString(m) }
func (*PostHousesRequest) ProtoMessage()    {}
func (*PostHousesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *PostHousesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostHousesRequest.Unmarshal(m, b)
}
func (m *PostHousesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostHousesRequest.Marshal(b, m, deterministic)
}
func (m *PostHousesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostHousesRequest.Merge(m, src)
}
func (m *PostHousesRequest) XXX_Size() int {
	return xxx_messageInfo_PostHousesRequest.Size(m)
}
func (m *PostHousesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostHousesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostHousesRequest proto.InternalMessageInfo

func (m *PostHousesRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *PostHousesRequest) GetMax() []byte {
	if m != nil {
		return m.Max
	}
	return nil
}

// 发布房源响应
type PostHousesResponse struct {
	Errno  string `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 返回房屋Id
	HouseId              int64    `protobuf:"varint,3,opt,name=HouseId,proto3" json:"HouseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostHousesResponse) Reset()         { *m = PostHousesResponse{} }
func (m *PostHousesResponse) String() string { return proto.CompactTextString(m) }
func (*PostHousesResponse) ProtoMessage()    {}
func (*PostHousesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *PostHousesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostHousesResponse.Unmarshal(m, b)
}
func (m *PostHousesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostHousesResponse.Marshal(b, m, deterministic)
}
func (m *PostHousesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostHousesResponse.Merge(m, src)
}
func (m *PostHousesResponse) XXX_Size() int {
	return xxx_messageInfo_PostHousesResponse.Size(m)
}
func (m *PostHousesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostHousesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostHousesResponse proto.InternalMessageInfo

func (m *PostHousesResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *PostHousesResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *PostHousesResponse) GetHouseId() int64 {
	if m != nil {
		return m.HouseId
	}
	return 0
}

// 上传房屋图片的请求
type HousesImageRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	// 房屋Id
	HouseId string `protobuf:"bytes,2,opt,name=HouseId,proto3" json:"HouseId,omitempty"`
	// 图片二进制
	Image []byte `protobuf:"bytes,3,opt,name=Image,proto3" json:"Image,omitempty"`
	// 图片大小
	FileSize int64 `protobuf:"varint,4,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	// 图片名称
	FileName             string   `protobuf:"bytes,5,opt,name=FileName,proto3" json:"FileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HousesImageRequest) Reset()         { *m = HousesImageRequest{} }
func (m *HousesImageRequest) String() string { return proto.CompactTextString(m) }
func (*HousesImageRequest) ProtoMessage()    {}
func (*HousesImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{5}
}

func (m *HousesImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HousesImageRequest.Unmarshal(m, b)
}
func (m *HousesImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HousesImageRequest.Marshal(b, m, deterministic)
}
func (m *HousesImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HousesImageRequest.Merge(m, src)
}
func (m *HousesImageRequest) XXX_Size() int {
	return xxx_messageInfo_HousesImageRequest.Size(m)
}
func (m *HousesImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HousesImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HousesImageRequest proto.InternalMessageInfo

func (m *HousesImageRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *HousesImageRequest) GetHouseId() string {
	if m != nil {
		return m.HouseId
	}
	return ""
}

func (m *HousesImageRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *HousesImageRequest) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *HousesImageRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

// 上传房屋图片的响应
type HousesImageResponse struct {
	Errno  string `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 图片Url
	ImgUrl               string   `protobuf:"bytes,3,opt,name=ImgUrl,proto3" json:"ImgUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HousesImageResponse) Reset()         { *m = HousesImageResponse{} }
func (m *HousesImageResponse) String() string { return proto.CompactTextString(m) }
func (*HousesImageResponse) ProtoMessage()    {}
func (*HousesImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{6}
}

func (m *HousesImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HousesImageResponse.Unmarshal(m, b)
}
func (m *HousesImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HousesImageResponse.Marshal(b, m, deterministic)
}
func (m *HousesImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HousesImageResponse.Merge(m, src)
}
func (m *HousesImageResponse) XXX_Size() int {
	return xxx_messageInfo_HousesImageResponse.Size(m)
}
func (m *HousesImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HousesImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HousesImageResponse proto.InternalMessageInfo

func (m *HousesImageResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *HousesImageResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *HousesImageResponse) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

// 获取房源详情的请求
type HouseInfoRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	HouseId              string   `protobuf:"bytes,2,opt,name=HouseId,proto3" json:"HouseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HouseInfoRequest) Reset()         { *m = HouseInfoRequest{} }
func (m *HouseInfoRequest) String() string { return proto.CompactTextString(m) }
func (*HouseInfoRequest) ProtoMessage()    {}
func (*HouseInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{7}
}

func (m *HouseInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseInfoRequest.Unmarshal(m, b)
}
func (m *HouseInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseInfoRequest.Marshal(b, m, deterministic)
}
func (m *HouseInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseInfoRequest.Merge(m, src)
}
func (m *HouseInfoRequest) XXX_Size() int {
	return xxx_messageInfo_HouseInfoRequest.Size(m)
}
func (m *HouseInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HouseInfoRequest proto.InternalMessageInfo

func (m *HouseInfoRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *HouseInfoRequest) GetHouseId() string {
	if m != nil {
		return m.HouseId
	}
	return ""
}

// 获取房源详情的响应
type HouseInfoResponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	HouseData            []byte   `protobuf:"bytes,3,opt,name=HouseData,proto3" json:"HouseData,omitempty"`
	UserId               int64    `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HouseInfoResponse) Reset()         { *m = HouseInfoResponse{} }
func (m *HouseInfoResponse) String() string { return proto.CompactTextString(m) }
func (*HouseInfoResponse) ProtoMessage()    {}
func (*HouseInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{8}
}

func (m *HouseInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseInfoResponse.Unmarshal(m, b)
}
func (m *HouseInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseInfoResponse.Marshal(b, m, deterministic)
}
func (m *HouseInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseInfoResponse.Merge(m, src)
}
func (m *HouseInfoResponse) XXX_Size() int {
	return xxx_messageInfo_HouseInfoResponse.Size(m)
}
func (m *HouseInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HouseInfoResponse proto.InternalMessageInfo

func (m *HouseInfoResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *HouseInfoResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *HouseInfoResponse) GetHouseData() []byte {
	if m != nil {
		return m.HouseData
	}
	return nil
}

func (m *HouseInfoResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// 搜索房源的请求
type SearchHousesRequest struct {
	// 区域编辑ID
	Aid string `protobuf:"bytes,1,opt,name=Aid,proto3" json:"Aid,omitempty"`
	// 开始时间
	Sd string `protobuf:"bytes,2,opt,name=Sd,proto3" json:"Sd,omitempty"`
	// 结束时间
	Ed string `protobuf:"bytes,3,opt,name=Ed,proto3" json:"Ed,omitempty"`
	// 查询方式
	Sk string `protobuf:"bytes,4,opt,name=Sk,proto3" json:"Sk,omitempty"`
	// 页码
	P                    string   `protobuf:"bytes,5,opt,name=P,proto3" json:"P,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchHousesRequest) Reset()         { *m = SearchHousesRequest{} }
func (m *SearchHousesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchHousesRequest) ProtoMessage()    {}
func (*SearchHousesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{9}
}

func (m *SearchHousesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchHousesRequest.Unmarshal(m, b)
}
func (m *SearchHousesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchHousesRequest.Marshal(b, m, deterministic)
}
func (m *SearchHousesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchHousesRequest.Merge(m, src)
}
func (m *SearchHousesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchHousesRequest.Size(m)
}
func (m *SearchHousesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchHousesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchHousesRequest proto.InternalMessageInfo

func (m *SearchHousesRequest) GetAid() string {
	if m != nil {
		return m.Aid
	}
	return ""
}

func (m *SearchHousesRequest) GetSd() string {
	if m != nil {
		return m.Sd
	}
	return ""
}

func (m *SearchHousesRequest) GetEd() string {
	if m != nil {
		return m.Ed
	}
	return ""
}

func (m *SearchHousesRequest) GetSk() string {
	if m != nil {
		return m.Sk
	}
	return ""
}

func (m *SearchHousesRequest) GetP() string {
	if m != nil {
		return m.P
	}
	return ""
}

// 搜索房源的响应
type SearchHousesResponse struct {
	Errno  string `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 当前页码
	CurrentPage int64  `protobuf:"varint,3,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	Houses      []byte `protobuf:"bytes,4,opt,name=Houses,proto3" json:"Houses,omitempty"`
	// 全部页码
	TotalPage            int64    `protobuf:"varint,5,opt,name=TotalPage,proto3" json:"TotalPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchHousesResponse) Reset()         { *m = SearchHousesResponse{} }
func (m *SearchHousesResponse) String() string { return proto.CompactTextString(m) }
func (*SearchHousesResponse) ProtoMessage()    {}
func (*SearchHousesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{10}
}

func (m *SearchHousesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchHousesResponse.Unmarshal(m, b)
}
func (m *SearchHousesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchHousesResponse.Marshal(b, m, deterministic)
}
func (m *SearchHousesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchHousesResponse.Merge(m, src)
}
func (m *SearchHousesResponse) XXX_Size() int {
	return xxx_messageInfo_SearchHousesResponse.Size(m)
}
func (m *SearchHousesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchHousesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchHousesResponse proto.InternalMessageInfo

func (m *SearchHousesResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *SearchHousesResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *SearchHousesResponse) GetCurrentPage() int64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *SearchHousesResponse) GetHouses() []byte {
	if m != nil {
		return m.Houses
	}
	return nil
}

func (m *SearchHousesResponse) GetTotalPage() int64 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.HouseSrv.Message")
	proto.RegisterType((*UserHousesRequest)(nil), "go.micro.srv.HouseSrv.UserHousesRequest")
	proto.RegisterType((*UserHousesResponse)(nil), "go.micro.srv.HouseSrv.UserHousesResponse")
	proto.RegisterType((*PostHousesRequest)(nil), "go.micro.srv.HouseSrv.PostHousesRequest")
	proto.RegisterType((*PostHousesResponse)(nil), "go.micro.srv.HouseSrv.PostHousesResponse")
	proto.RegisterType((*HousesImageRequest)(nil), "go.micro.srv.HouseSrv.HousesImageRequest")
	proto.RegisterType((*HousesImageResponse)(nil), "go.micro.srv.HouseSrv.HousesImageResponse")
	proto.RegisterType((*HouseInfoRequest)(nil), "go.micro.srv.HouseSrv.HouseInfoRequest")
	proto.RegisterType((*HouseInfoResponse)(nil), "go.micro.srv.HouseSrv.HouseInfoResponse")
	proto.RegisterType((*SearchHousesRequest)(nil), "go.micro.srv.HouseSrv.SearchHousesRequest")
	proto.RegisterType((*SearchHousesResponse)(nil), "go.micro.srv.HouseSrv.SearchHousesResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5f, 0x73, 0xd2, 0x40,
	0x10, 0x6f, 0xa0, 0x05, 0x59, 0xd1, 0xc2, 0xb5, 0x76, 0x32, 0xb4, 0x0f, 0xcc, 0xbd, 0x88, 0x3a,
	0x13, 0x47, 0xfd, 0x04, 0x4e, 0x45, 0xc4, 0x19, 0x1c, 0x26, 0x69, 0x9f, 0xf4, 0xe5, 0x84, 0x6d,
	0x8c, 0x4d, 0x72, 0x78, 0x17, 0x2a, 0xfa, 0x3d, 0x7c, 0x71, 0xfc, 0xb0, 0xce, 0xfd, 0x09, 0x09,
	0x43, 0x51, 0xc4, 0x27, 0xee, 0xb7, 0xb7, 0xfb, 0xdb, 0xdf, 0x2e, 0xbb, 0x17, 0x38, 0x9d, 0x09,
	0x9e, 0xf1, 0xa7, 0xb8, 0x60, 0xc9, 0x2c, 0xc6, 0xfc, 0xd7, 0xd3, 0x56, 0xf2, 0x20, 0xe4, 0x5e,
	0x12, 0x4d, 0x04, 0xf7, 0xa4, 0xb8, 0xf1, 0xde, 0xf0, 0xb9, 0xc4, 0x40, 0xdc, 0xd0, 0x53, 0xa8,
	0x8f, 0x50, 0x4a, 0x16, 0x22, 0x69, 0x41, 0x55, 0xb2, 0x6f, 0xae, 0xd3, 0x75, 0x7a, 0x0d, 0x5f,
	0x1d, 0xe9, 0x33, 0x68, 0x5f, 0x4a, 0x14, 0xda, 0x59, 0xfa, 0xf8, 0x65, 0x8e, 0x32, 0x23, 0x67,
	0xd0, 0x08, 0x50, 0xca, 0x88, 0xa7, 0xc3, 0xa9, 0x75, 0x2e, 0x0c, 0xf4, 0x02, 0x48, 0x39, 0x44,
	0xce, 0x78, 0x2a, 0x91, 0x1c, 0xc3, 0x41, 0x5f, 0x88, 0x94, 0x5b, 0x7f, 0x03, 0xc8, 0x09, 0xd4,
	0xfa, 0x42, 0x8c, 0x64, 0xe8, 0x56, 0xb4, 0xd9, 0x22, 0x25, 0x64, 0x14, 0x2d, 0xdc, 0x6a, 0xd7,
	0xe9, 0x35, 0x7d, 0x75, 0xa4, 0xe7, 0xd0, 0x1e, 0x73, 0x99, 0xfd, 0x83, 0x10, 0x4d, 0xc2, 0x16,
	0x9a, 0x59, 0x91, 0xb0, 0x05, 0xfd, 0x00, 0xa4, 0x4c, 0xb2, 0x93, 0x34, 0x17, 0xea, 0x3a, 0x7e,
	0x38, 0xd5, 0xf2, 0xaa, 0x7e, 0x0e, 0xe9, 0x4f, 0x07, 0x88, 0xa1, 0x1e, 0x26, 0x2c, 0xc4, 0xed,
	0x44, 0x96, 0xe8, 0x4c, 0x9e, 0x1c, 0x2a, 0x59, 0x9a, 0xc7, 0x76, 0xc1, 0x00, 0xd2, 0x81, 0x3b,
	0xaf, 0xa3, 0x18, 0x83, 0xe8, 0x3b, 0xba, 0xfb, 0x3a, 0xff, 0x12, 0xe7, 0x77, 0xef, 0x58, 0x82,
	0xee, 0x81, 0x26, 0x5b, 0x62, 0xfa, 0x1e, 0x8e, 0x56, 0xb4, 0xed, 0x54, 0xfb, 0x09, 0xd4, 0x86,
	0x49, 0x78, 0x29, 0x62, 0xad, 0xa9, 0xe1, 0x5b, 0x44, 0xdf, 0x42, 0xcb, 0xa8, 0x4e, 0xaf, 0xf8,
	0x7f, 0x96, 0x4d, 0xbf, 0x42, 0xbb, 0xc4, 0xb5, 0x93, 0xcc, 0x33, 0x68, 0x68, 0x8a, 0x57, 0x2c,
	0x63, 0xb6, 0x7b, 0x85, 0x41, 0x45, 0xa9, 0xf9, 0x1c, 0x4e, 0x6d, 0xff, 0x2c, 0xa2, 0x08, 0x47,
	0x01, 0x32, 0x31, 0xf9, 0xb4, 0x3a, 0x63, 0x2d, 0xa8, 0xbe, 0x8c, 0xf2, 0x0a, 0xd4, 0x91, 0xdc,
	0x87, 0x4a, 0x90, 0xcb, 0xae, 0x04, 0x1a, 0xf7, 0xa7, 0xb6, 0x23, 0x95, 0xbe, 0xb9, 0xbf, 0xd6,
	0xe4, 0xea, 0xfe, 0x9a, 0x34, 0xc1, 0x19, 0xdb, 0xff, 0xc3, 0x19, 0xd3, 0x5f, 0x0e, 0x1c, 0xaf,
	0xe6, 0xd9, 0xa9, 0xc6, 0x2e, 0xdc, 0x3d, 0x9f, 0x0b, 0x81, 0x69, 0x36, 0xce, 0x67, 0xa4, 0xea,
	0x97, 0x4d, 0x2a, 0xd2, 0x64, 0xd0, 0x52, 0x9a, 0xbe, 0x45, 0xaa, 0x3b, 0x17, 0x3c, 0x63, 0xb1,
	0x8e, 0x3b, 0xd0, 0x71, 0x85, 0xe1, 0xf9, 0x8f, 0x7d, 0xa8, 0xf7, 0xcd, 0xb3, 0x41, 0xae, 0xe0,
	0xde, 0x00, 0xb3, 0x62, 0x99, 0x49, 0xcf, 0xbb, 0xf5, 0x09, 0xf1, 0xd6, 0x9e, 0x88, 0xce, 0xa3,
	0x2d, 0x3c, 0x4d, 0xdd, 0x74, 0x8f, 0x4c, 0x00, 0x8a, 0xb5, 0xdc, 0x98, 0x64, 0x6d, 0xfd, 0x37,
	0x26, 0x59, 0xdf, 0x71, 0xba, 0x47, 0x3e, 0xc3, 0x61, 0x61, 0x37, 0xbb, 0xb4, 0x29, 0x7e, 0x7d,
	0x89, 0x3b, 0x8f, 0xb7, 0x71, 0x2d, 0x15, 0xd4, 0x1c, 0x60, 0xb6, 0x1c, 0x63, 0xf2, 0xf0, 0x4f,
	0xd1, 0xa5, 0xa5, 0xe9, 0xf4, 0xfe, 0xee, 0xb8, 0x4c, 0x12, 0xc3, 0xe1, 0x00, 0xb3, 0xf2, 0x28,
	0x91, 0x4d, 0x2a, 0x6f, 0x99, 0xeb, 0xce, 0x93, 0xad, 0x7c, 0xf3, 0x6c, 0x1f, 0x6b, 0xfa, 0x1b,
	0xf2, 0xe2, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xb3, 0x72, 0x32, 0x62, 0x06, 0x00, 0x00,
}
